require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ReactNativeWill' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'ReactNativeWillTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_frameworks!
end

IOS_VERSION = '11.0'

post_install do |installer|
  react_native_post_install(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_VERSION
      # config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
      config.build_settings['ARCHS'] = '${ARCHS_STANDARD_64_BIT}'
    end

    case target.name
    when 'RCT-Folly'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end